
# Generated by Django 5.0.6 on 2024-07-04 11:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProjectsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Data_Id', models.CharField(max_length=255)),
                ('Label', models.CharField(max_length=255)),
                ('Modularity_Class', models.CharField(max_length=255)),
                ('Pageranks', models.CharField(max_length=255)),
                ('Custom_Filter', models.CharField(max_length=255)),
                ('X', models.CharField(max_length=255)),
                ('Y', models.CharField(max_length=255)),
                ('Size', models.CharField(max_length=255)),
                ('Color', models.CharField(max_length=255)),
                ('Level1', models.CharField(max_length=255)),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file_handler.userprojects')),
            ],
        ),
        migrations.CreateModel(
            name='UserProjectShapes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shape_data', models.JSONField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file_handler.userprojects')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]

