# Generated by Django 5.0.6 on 2024-08-08 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_handler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllLabels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_id', models.CharField(max_length=255)),
                ('label', models.CharField(max_length=255)),
            ],
        ),
    ]
